apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-injector-deployment
  labels: 
    keel.sh/policy: force
    keel.sh/trigger: webhooks
    keel.sh/approvals: "0"
    keel.sh/match-tag: "true"
spec:
  selector:
    matchLabels:
      app: workflow-injector-ins
  replicas: 1
  template:
    metadata:
      labels:
        app: workflow-injector-ins
    spec:
      containers:
        - name: workflow-injector-ins
          imagePullPolicy: Always 
          image: harbor.cloudcontrolsystems.cn/workflow/injector:latest
          volumeMounts:
            - name: kubeconfig-volume
              mountPath: "/root/.kube"
          env:
            - name: ACTION_ON_FINISH
              value: 'sleep'
            - name: TEST_WITH_ARGO
              value: 'true'
      volumes:
        - name: kubeconfig-volume
          configMap:
            name: workflow-ingector-configmap
            items:
              - key: kubeconfig
                path: config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-ingector-configmap
data:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR1RENDQXFDZ0F3SUJBZ0lVY0ZUbXJZdk5UTkZCcjVRQkdvLy9TWlliSXA0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1lURUxNQWtHQTFVRUJoTUNRMDR4RVRBUEJnTlZCQWdUQ0VoaGJtZGFhRzkxTVFzd0NRWURWUVFIRXdKWQpVekVNTUFvR0ExVUVDaE1EYXpoek1ROHdEUVlEVlFRTEV3WlRlWE4wWlcweEV6QVJCZ05WQkFNVENtdDFZbVZ5CmJtVjBaWE13SUJjTk1qRXdOVEk1TWpBeU1qQXdXaGdQTWpFeU1UQTFNRFV5TURJeU1EQmFNR0V4Q3pBSkJnTlYKQkFZVEFrTk9NUkV3RHdZRFZRUUlFd2hJWVc1bldtaHZkVEVMTUFrR0ExVUVCeE1DV0ZNeEREQUtCZ05WQkFvVApBMnM0Y3pFUE1BMEdBMVVFQ3hNR1UzbHpkR1Z0TVJNd0VRWURWUVFERXdwcmRXSmxjbTVsZEdWek1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXhDTEthR1VLemJXcUVOUE1qNWFhL1BQQlVZS1gKRkY5Zy80RzM1QjBubFFHbkM5S1JrUzJUWm1QWHY0RnR2WEJVU24rMHdnRVY1bDFEOXJGSUNRZDdwWVJISTRnbQpjdXJYeExaeTNxS3JwYnRWODBvWFc0VDlhVCtHNGFCSDFyU3I0UUoyZ3g5WUcvS2puQlFJRFVkcHk2NmRGR2JpCkZuWnp1TXd0TXRxakF5SlY3c08vYUpHSEl2MzZVSzNSTFNNSW03SkMwcWYwOVRjMDJYY29SeHRxaUdQaVBpZ1EKemRpOURsbHBXdW5qMGpqM0tUd2tqWTc3dWR2TGJWZ2JlQVI0YUtLRWc2b1FTMGhqVWpNNEYrRlhRUG51b250aQo4TnR0RnJ2aWZ6OUFQamR5anBkSEZBLzBzaGIvdjV2bUxoWWI0c0pxZ2NGQmVxbTB4SXdFaE9YSGRRSURBUUFCCm8yWXdaREFPQmdOVkhROEJBZjhFQkFNQ0FRWXdFZ1lEVlIwVEFRSC9CQWd3QmdFQi93SUJBakFkQmdOVkhRNEUKRmdRVVc0bUVqTVFORDQ4b0RnU04wMy81K1VsSzc3RXdId1lEVlIwakJCZ3dGb0FVVzRtRWpNUU5ENDhvRGdTTgowMy81K1VsSzc3RXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQjlkd3lCUmdJalZOdVVIM3hNNWV1L3lXbDNkCi83NmluM1Y5UzZyc2NGUVZVVXRVZjBhWjBWb3NUcGJNNTErdXI4S3ExK21iRmw5L3dnUmRtUXJrZWVYZEdaL1MKcCt3eE15clZFQVdaTVhMdDdOeDNnRkZ5ZjcyM0Npdk9yTHZ2STQxWk9SZjl0SDBKbGI4ZTJkM2JFNGVJOU1RdgpGY3MwNjgrNzJ4dGczT0w0YWpwNThjVTRFVGx6Z2lWcW81elJpRkJOTlJwWGVON3lxSFE2RzJxNjBRVi9mdVpqClFUcTYwY1pJRit3WEFwdnhpYjNXUmFaZWQyVEU5ZTZNODVGUC9LQUN5QU9BSWZkVmJDOG54TktWNEhKd285L3cKdkJiUEYyZ0hYVVJBWEd5eTljMTIvb01hSndLSGE0eU1jWlVPV1llNEJFMVp4TEdFcWZTTkU3azdBd0E9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        server: https://172.28.0.2:6443
      name: cluster1
    contexts:
    - context:
        cluster: cluster1
        user: admin
      name: context-cluster1
    current-context: context-cluster1
    kind: Config
    preferences: {}
    users:
    - name: admin
      user:
        client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQxekNDQXIrZ0F3SUJBZ0lVUUpkdkluKzhUN2xaNlE1OFkybFRiSGJaZlVrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1lURUxNQWtHQTFVRUJoTUNRMDR4RVRBUEJnTlZCQWdUQ0VoaGJtZGFhRzkxTVFzd0NRWURWUVFIRXdKWQpVekVNTUFvR0ExVUVDaE1EYXpoek1ROHdEUVlEVlFRTEV3WlRlWE4wWlcweEV6QVJCZ05WQkFNVENtdDFZbVZ5CmJtVjBaWE13SUJjTk1qRXdOVEk1TWpBeU1qQXdXaGdQTWpBM01UQTFNVGN5TURJeU1EQmFNR2N4Q3pBSkJnTlYKQkFZVEFrTk9NUkV3RHdZRFZRUUlFd2hJWVc1bldtaHZkVEVMTUFrR0ExVUVCeE1DV0ZNeEZ6QVZCZ05WQkFvVApEbk41YzNSbGJUcHRZWE4wWlhKek1ROHdEUVlEVlFRTEV3WlRlWE4wWlcweERqQU1CZ05WQkFNVEJXRmtiV2x1Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBNjZvODhOclZmMndsOGxaY1BOK0MKUjhoZTRtdkl3NEV5OFRNOU1vYkkvb1JYejVPZ3VWQSs0NnREQklJc3Z2QnBPRmlqVm1rMDVNUGozb2ZxbFRHcwo4Ym5YRmdFdlhEU2RtTW9NNk5OdWlrbitUZWZLYnN3dG1IMlBXcVljckMxUHE1eC9IZTFYbUpTVSthZHliN1YxCmV2U09mZCt3aWZrZUlVWDhCd3hWU1ErVEFHaVA1SjlNR2xhTlVwTk85RS95enh2UEZwcE5hcDVzZDVFVURXeTUKaWcvajlGZFFGTzhpekhxTG1yNlRQZWp4S013ZG1DZlY0TzZQQ1pWZUJNV2p1QmVkT3ovaVkyOWlZK2ZRSlg1Qwo5ZUpORVhORmpsSk5zZEtYeVJsVFdwM05UbW50ODFvY1lZMVNyTW9VcVRnejBzS3pPRnZHSVJOaXJaaVp6MjExClJ3SURBUUFCbzM4d2ZUQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUVGTittZXRGRGFxWnByQzdlMENWdwoxRVZlNUZZZ01COEdBMVVkSXdRWU1CYUFGRnVKaEl6RURRK1BLQTRFamROLytmbEpTdSt4TUEwR0NTcUdTSWIzCkRRRUJDd1VBQTRJQkFRQlRDWHorODJlWVp5Nk83SFp5MUJxUnJ5R1RPRisrSnJ5RnZzS0MwRmsrdms1QU5RTlkKZGdRR3U2WlI5ZEt5Z2prMDE5aFY3dnkrRjg3RDFRcG9tTm5PamtIUFNrNmc4VVdmbG5IeGgxVWdXTkcvcnlSRwpDeEt4U1daSXNhbWZ5NUdKVkUwSUlxSGIrbFZ4T2tOMWIvbTczd29QMGgzRlJURkZTbEhDMTZNNStGd2UwZ21DCjFCQ0JoVUdBS0xuOHNpenIwZWRYZHN4elQyMllqelpURlhiYXJHVC9hQmJRZTdCcUVudVZ5QmNqK2labElSMFYKOGF3ZVE1OHdRRlRYSXBIa1VOR2JQSEtRbFVQSWFVRzV5enlWdkZxRW9iNHlJajFaSkdkUjdrNjZnNUpsYmFBNAp2VzVxQVNoL3Npd2F3V3RtMzhxM1hqdDdiQldyVjF2K3h4RUoKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBNjZvODhOclZmMndsOGxaY1BOK0NSOGhlNG12SXc0RXk4VE05TW9iSS9vUlh6NU9nCnVWQSs0NnREQklJc3Z2QnBPRmlqVm1rMDVNUGozb2ZxbFRHczhiblhGZ0V2WERTZG1Nb002Tk51aWtuK1RlZksKYnN3dG1IMlBXcVljckMxUHE1eC9IZTFYbUpTVSthZHliN1YxZXZTT2ZkK3dpZmtlSVVYOEJ3eFZTUStUQUdpUAo1SjlNR2xhTlVwTk85RS95enh2UEZwcE5hcDVzZDVFVURXeTVpZy9qOUZkUUZPOGl6SHFMbXI2VFBlanhLTXdkCm1DZlY0TzZQQ1pWZUJNV2p1QmVkT3ovaVkyOWlZK2ZRSlg1QzllSk5FWE5GamxKTnNkS1h5UmxUV3AzTlRtbnQKODFvY1lZMVNyTW9VcVRnejBzS3pPRnZHSVJOaXJaaVp6MjExUndJREFRQUJBb0lCQVFDUkVPd09mMGFvOTFPcwpoMGlrR0JuRVFpMVdSMjhBR2NuWCsraVI3N0pPS2YwN3crNU41SDJ4Kzd4M1RBSnJUdVlXVDBuTWFWcXI3NEdYCmZDY0V5OTFmdHp3VlNZbHp3dGU0TTdnYW9md0xtRnk0YkJTS2U1a2RvenpaV2lPUVFSd24wVi9XZGtGVHBUTEgKTXpJWVhhVUJtUVVWcXRxck0vUStHeXgyMGpxMWkzZ21NTmlqWWhQU0UycWlkRVVBc1hUc1VMRnBRT1l5UkNEWQpPOThRMDAwbnhKbm8rYUYxbndHMW9wT0EyMzJFbmk1cVNCb1ZaOGNkQlk5bHcxaU1QekFHVGVzMDM2TnpFUG5tCjJNWDc3d0h3SlNYSTg3ZUFWUnJZSDhhdjllVU0zS1YzclNrYUwwNXZRU1VtMXdpU3BHYWlMVWV6dHViTU96dzcKNFhiSktNeHhBb0dCQU8wVHpkK0tpbEhrY01BU3N6RnFObzRCWFNTcVladDZwdVNkMzFsajJJdEsvS0pPNms4NQpyZExwNEpFOEZ1dWJFZ2hFanB3WWhKOWkyb01ML0xtRS9CU3VtSHBKTVdudG5UTWc3NVRqSCt5RCszZFovT3lJCm94UHVxTFRMcEJRT2twNDAvUTArM1BwMWZab1BaVnJTWEl0em1SWVVaRTlINUY0SGpXQ0xpb3U3QW9HQkFQNTUKa3pJVk0yRG91YjYrZEdGN3l3QTVuL2Q4WFBJSTROVEw2MkRhWUJITVNFSVVsS3lXK05LUXVoU0xEbDFhSlFHdwpFekNyYkk5ZHJEUFNING5XUVpGV1pRdkF6dVdYQWE3R0s0TXo2MWRHZHV2MjFZU3hmRHlJcytPR1dEMmtjUnR6CmFxb2NRN1pZY3dySzArdDNEbmRoQU55N01kRURvdkJ6Q2VaSXhuWGxBb0dCQU56SDNLbVk4MGRnWGtBQktpK1MKb2t1TXFabERzcktBZm52WktlNnROVFJER1JKdU8zYWNXR3hhc1crUGJpanJ1TmRLUVNUTkVIVCtNbEJvRVdzVApsVTROYXFJM0YzVjJlemJxTFRPU2NHQnFhUHkxS1AxK0lhQ21XU1pGbnYrdXNvdnkvTllnL05taUlONGdDRnVVCkcrc2lOQ2FEeHdhdUJOWXNZbFRPbnErUkFvR0FHMS9rcjd5TUhGNnNySkk4WHNnOFhEZld0MzdQV05JUHJaU0sKSzQ4U1NwZlpKaEtrczdSQjdCVFpqNkF0MldqN0ZpVmt5eFdGeGg1amllZU9zUHMxYm5jR3c2N29FdGFkdmJsZgpzT3VDNDQ2VytHZERMTlVTOGtnYVlkMXYzS0cxOFNnSFQybGU5MXlvYzM3Q01WQkxaQmd4U1kxeG5IUnhzTUFQClRwQ0JtT2tDZ1lFQXB0Q2VkandQdHBiNHRUR2Nlamt2QUJSTTJTUUMvUmJkWGN4Y2FlcHlCOUowek1TTno2YlMKSXliRzRQSzA2ckpxYTFBUDFBUHluQzJKdmpwM0VwaUZLQTMzKy8rU3lZbzdWWEs3aXl2T3cyMVFjdkFEakdWVApYbTlSM3pCenl0WnQ5RG5OM01yUWRaMkwvUUtZdGIyOFhiR0tiN2t1ejNNakhHbWQzVlVkWU1jPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
